WebApplication1/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    //[Authorize]
    public class OrderController : Controller
    {

        // GET: OrderController
        private readonly ProductWarehouseContext context;
        DAO dao= new DAO();
        public OrderController(ProductWarehouseContext context)
        {
            this.context = context;
        }
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            //if (HttpContext.Session.GetString("username")!=null)
            //{
                //ViewBag.Session=HttpContext.Session.GetString("username");
                var customers = context.Orders.OrderBy(c => c.Id);

                var customerProcedure = dao.GetOrdersProcedure(page, pageSize);
                int totalCount = customers.Count();
                int totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

                // customers = (IOrderedQueryable<Order>)customers.Skip((page - 1) * pageSize).Take(pageSize);

                ViewBag.TotalCount = totalCount;
                ViewBag.TotalPages = totalPages;
                ViewBag.CurrentPage = page;
                ViewBag.PageSize = pageSize;

                return View(customerProcedure);
            //}
            //else
            //{              
            //    return RedirectToAction("Index","Login");
            //}
           
        }
        [HttpGet]
        public IActionResult GetProducts(string keyword)
        {
            var products = context.Products
                .Where(p => p.Name.Contains(keyword))
                .Select(p => new { label = p.Name, value = p.Id })
                .ToList();

            return Json(products);
        }

        [HttpPost]
        public ActionResult Edit([FromBody] OrderModel model)
        {
            try
            {
                List<OrderDetails> orderDetails = model.OrderDetails;
                if (orderDetails.Count == 0)
                {
                    return BadRequest("Null value");
                }
                string selectedItem = model.SelectedItem;
              bool delete=  dao.DeleteAllOrder(model.OrderId);
                
                    foreach (var o in orderDetails)
                    {
                        OrderProduct op = new OrderProduct();
                        op.ProductId = o.productId;
                        op.OrderId = model.OrderId;
                        op.Quantity = o.quantity;
                        op.Price = o.price;                      
                        context.OrderProducts.Add(op);
                        context.SaveChanges();
                    }
                    return Ok(orderDetails[0].productId.ToString() + " " + selectedItem);
               
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpPost]
        public IActionResult Save([FromBody] OrderModel model)
        {
            try
            {
                List<OrderDetails> orderDetails = model.OrderDetails;
                if (orderDetails.Count == 0)
                {
                    return BadRequest("Null value");
                }
                string selectedItem = model.SelectedItem;
                Order order = new Order();
                order.OrderType = selectedItem;
                order.OrderDate = DateTime.Now;
               
                    order.CreatedBy = "tuyennh";
                
                    
                context.Orders.Add(order);
                context.SaveChanges();
                foreach (var o in orderDetails)
                {
                    OrderProduct op = new OrderProduct();
                    op.ProductId = o.productId;
                    op.OrderId = order.Id;
                    op.Quantity = o.quantity;
                    op.Price = o.price;
                    context.OrderProducts.Add(op);
                    context.SaveChanges();
                }
                return Ok(orderDetails[0].productId.ToString() + " " + selectedItem);
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }          
        }
        // GET: OrderController/Edit/5
        public ActionResult Edit(int id, string type)
        {
           
            List<OrderDetails> list = dao.GetOrderDetails(id);
            OrderModel order = new OrderModel();
            order.OrderId = id;
            order.OrderDetails = list;  
            order.SelectedItem = type;
            return View(order);
        }
        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = dao.GetOrderDetailsByID(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewBag.OrderD = order.ToList();
            return View();
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            var product= context.Products.ToList();
            return View(product);
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

      

        // POST: OrderController/Edit/5
        

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ReportController : Controller
    {
        DAO dao = new DAO();
        public IActionResult Report(string type)
        {
            if (type == null)
            {
                type = "import";
            }
            ViewBag.Type = type;    
            return View(dao.ReportProductQuantity(type));
        }
    }
}

WebApplication1/Views/Header/Header.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
          rel="stylesheet" />
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
          rel="stylesheet" />
    <title>Bootstrap Example</title>
   
</head>
<body class="p-3 m-0 border-0 bd-example">
    <!-- Example Code -->

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Quản lý kho</a>
            <button class="navbar-toggler collapsed"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse"
                 id="navbarSupportedContent"
                 style="">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Order" asp-action="Index">Đơn hàng</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="#"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Báo cáo
                        </a>
                        <ul class="dropdown-menu" style="width: fit-content;">
                            <li><a class="dropdown-item" asp-controller="Report" asp-action="Report" asp-route-type="import">Nhập kho</a></li>
                            <li><a class="dropdown-item" asp-controller="Report" asp-action="Report" asp-route-type="export">Xuất kho</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- End Example Code -->
</body>
</html>